trigger:
- master

pool:
  vmImage: windows-latest

variables:
  restoreFeedName: 'ECAR/EC.ECAR.Packages'
  pushFeedName: 'EC.Packages'
  GitVersion.SemVer: ''

resources:
  repositories:
    - repository: YAMLTemplates
      type: git
      name: 'ECAR DevOps/ECAR.DevOps.YamlTemplates'

steps:
#Call .NET_Framework_Build_and_Restore template 
- template: RestoreAndBuild.NET_Framework_Lib.yml@YAMLTemplates
  parameters:
    vstsFeedName: $(restoreFeedName)

#Call NuGet_Pack\Push_+_Tag_Git_Repo (SDK) template (only if triggered by master branch commit)
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - template: PackPushAndTag.NET_SDK_Lib.yml@YAMLTemplates
    parameters: 
      vstsFeedName: $(pushFeedName)
      tag: 'v$(GitVersion.SemVer)'