name: $(BuildDefinitionName)-$(Rev:r)

pool:
  vmImage: windows-latest

trigger: none

resources:
  repositories:
    - repository: BuildTemplates
      type: git
      name: 'ECAR DevOps/BuildTemplates'

steps:
- template: NuGet.NET.Framework.DocuSign.yml@BuildTemplates
  parameters:
    buildName: $(Build.BuildNumber)
    artifactStagingDir: $(build.artifactStagingDirectory)
    feedName: 'ECAR/EC.ECAR.Packages'
    buildConfiguration: Debug