trigger:
- master

pool:
  vmImage: windows-latest

variables:
- group: ECAR Variable Group
- name: GitVersion.SemVer

resources:
  repositories:
    - repository: YAMLTemplates
      type: git
      name: 'ECAR DevOps/ECAR.DevOps.YamlTemplates'

steps:
#Call .NET_Framework_Build_and_Restore template 
- template: RestoreAndBuild.NET_Framework_Lib.yml@YAMLTemplates
  parameters:
    vstsFeedName: $(ECARPackageFeed)

#Call NuGet_Pack\Push_+_Tag_Git_Repo (SDK) template (only if triggered by master branch commit)
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - template: PackPushAndTag.NET_Framework_Lib.yml@YAMLTemplates
    parameters:
      whatToPack: '../ECAR.DocuSign/ECAR.DocuSign.nuspec'
      vstsFeedName: $(ECARPackageFeed)
      tag: 'v$(GitVersion.SemVer)'