//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECAR.DocuSign.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECAR.DocuSign.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocuSign configuration not set..
        /// </summary>
        internal static string DSCONFIG_NOT_SET {
            get {
                return ResourceManager.GetString("DSCONFIG_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch ID cannot be null or blank..
        /// </summary>
        internal static string EMPTY_BATCHID_VALUE {
            get {
                return ResourceManager.GetString("EMPTY_BATCHID_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocuSign document ID cannot be null or blank..
        /// </summary>
        internal static string EMPTY_DOCUMENT_ID {
            get {
                return ResourceManager.GetString("EMPTY_DOCUMENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocuSign envelope ID cannot be null or blank..
        /// </summary>
        internal static string EMPTY_ENVELOPE_ID {
            get {
                return ResourceManager.GetString("EMPTY_ENVELOPE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all recipients included in the current batch have an associated signer ID..
        /// </summary>
        internal static string EMPTY_SIGNER_ID_FOR_BATCH {
            get {
                return ResourceManager.GetString("EMPTY_SIGNER_ID_FOR_BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be null or blank..
        /// </summary>
        internal static string EMPTY_STARTDATE_VALUE {
            get {
                return ResourceManager.GetString("EMPTY_STARTDATE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocuSign tab label cannot be null or blank..
        /// </summary>
        internal static string EMPTY_TAB_LABEL {
            get {
                return ResourceManager.GetString("EMPTY_TAB_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name cannot be null or blank..
        /// </summary>
        internal static string EMPTY_TEMPLATE_NAME {
            get {
                return ResourceManager.GetString("EMPTY_TEMPLATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voided reason cannot be null or blank..
        /// </summary>
        internal static string EMPTY_VOIDED_REASON {
            get {
                return ResourceManager.GetString("EMPTY_VOIDED_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named field: &apos;{0}&apos; was not found in the DocuSign document..
        /// </summary>
        internal static string FIELD_x_NOT_FOUND {
            get {
                return ResourceManager.GetString("FIELD_x_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified envelope status is invalid for event notification from DocuSign: &apos;{0}&apos;..
        /// </summary>
        internal static string INVALID_STATUS_FOR_EVENTNOTIFICATION_x {
            get {
                return ResourceManager.GetString("INVALID_STATUS_FOR_EVENTNOTIFICATION_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocuSign template not found: &apos;{0}&apos;..
        /// </summary>
        internal static string TEMPLATE_NOT_FOUND_x {
            get {
                return ResourceManager.GetString("TEMPLATE_NOT_FOUND_x", resourceCulture);
            }
        }
    }
}
